language: ruby

rvm:
  - 1.9.3

bundler_args: --without development

branches:
  only:
    - master
    - develop

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  email:
    - rubeque@scimedsolutions.com

services: mongodb

env:
  - SECRET_TOKEN='680bebab66e8203113df70e0e8ba9294ac87545b86037410e29ec48d2b05510c57d3809be50ed093774d4874b37b69342b6d04cfcfcb60c1b249daad726e551c'

